### PR TITLE
Add Speed and Cadence profile

### PR DESCRIPTION
**Pull request by half2me**
Added support for the ANT+ Speed & Cadence profile

### CODE REVIEW

**Comment by half2me** [comment]
@cujomalainey should I be basing these off of the `development` branch instead?

**Comment by cujomalainey** [comment]
> @cujomalainey should I be basing these off of the `development` branch instead?

ideally yes, the work around ANT+ is much farther over there. I was going to cherry pick over your other PR when I had the chance as well.

**Comment by half2me** [comment]
@cujomalainey would you like me to rebase this off of `development` then?

**Comment by cujomalainey** [comment]
> @cujomalainey would you like me to rebase this off of `development` then?

Yes please, also if you can drop the merge commit that would be appreciated. I meant to do a rebase to merge your last change

**Comment by half2me** [comment]
closing in favour of #9

**Pull request closed without merging**
